---
documentclass: ctexart

includes: fancyhdr,geometry
pagestyle: fancy
fancypagestyle: plain
geometry: "a4paper,left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm"


title: \vspace{-4em}{第4章时间序列分析作业}
author:
  - 应用统计学16 2016310868 郑昊亮

output:
  rticles::ctex:
    keep_tex: yes
    fig_caption: no
    number_sections: no
    toc: no 
classoption: "hyperref,"
---
## 4.2
首先借助*ARMAacf*函数计算数值 
```{r}
ACF_4.2a = ARMAacf(ma = c(-0.5,-0.4));
ACF_4.2b = ARMAacf(ma = c(-1.2,0.7));
ACF_4.2c = ARMAacf(ma = c(1,0.6));
```

然后自定义*ACFplot*函数用于绘图

```{r echo=TRUE,eval=FALSE}
ACFplot = function(acf)
{
  plot(y = acf[-1], x = 1:(length(acf)-1), 
       main=substitute(acf), xlab = "Lag", ylab = "ACF", type = c("h"),  xaxt="n")
  abline(h = 0)
  axis(at = 1:(length(acf)-1), side = 1)
  points(y = acf[-1], x = 1:(length(acf)-1), pch = 20)
}

op = par(mfrow=c(2,2))
ACFplot(ACF_4.2a)
ACFplot(ACF_4.2b)
ACFplot(ACF_4.2c)
```

\vspace{-2em}
```{r echo=FALSE,eval=TRUE}
ACFplot = function(acf)
{
  plot(y = acf[-1], x = 1:(length(acf)-1), 
       main=substitute(acf), xlab = "Lag", ylab = "ACF", type = c("h"),  xaxt="n")
  abline(h = 0)
  axis(at = 1:(length(acf)-1), side = 1)
  points(y = acf[-1], x = 1:(length(acf)-1), pch = 20)
}

op = par(mfrow=c(2,2))
ACFplot(ACF_4.2a)
ACFplot(ACF_4.2b)
ACFplot(ACF_4.2c)
```

## 4.4
根据 MA(1) 自相关函数公式，代入可得
$$
\frac{-\frac{1}{\theta}}{1+(\frac{1}{\theta})^2} = \frac{-\theta}{1+\theta^2} =\rho_1 
$$
\noindent 因此不变。

## 4.5
自相关函数计算结果如下：
```{r}
ACF_4.5a = ARMAacf(ar = 0.6, lag.max = 10); ACF_4.5a
ACF_4.5b = ARMAacf(ar = -0.6, lag.max = 10); ACF_4.5b
ACF_4.5c = ARMAacf(ar = 0.95, lag.max = 20); ACF_4.5c
ACF_4.5d = ARMAacf(ar = 0.3, lag.max = 10); ACF_4.5d
```

画图：
```{r}
op = par(mfrow=c(2,2))
ACFplot(ACF_4.5a)
ACFplot(ACF_4.5b)
ACFplot(ACF_4.5c)
ACFplot(ACF_4.5d)
```


## 4.10

```{r}
ACF_4.10a = ARMAacf(ar = 0.7, ma = -0.4, lag.max = 15);
ACF_4.10b = ARMAacf(ar = 0.7, ma = 0.4, lag.max = 15);

op = par(mfrow=c(1,2))
ACFplot(ACF_4.10a)
ACFplot(ACF_4.10b)
```

## 4.16
### (a)
将该式代入$Y_{t-1}$得：

$$
\begin{aligned}
3Y_{t-1}+e_t &= 3*-\sum_{j=1}^\infty(1/3)^j e_{t-1+j}+e_t\\
             &= -\sum_{j=1}^\infty(1/3)^{j-1} e_{t-1+j}+e_t\\
             &= -\sum_{k=0}^\infty(1/3)^{k} e_{t+k}+e_t\\
             &= -e_t - \sum_{k=1}^\infty(1/3)^k e_{t+k}+e_t\\
             &= - \sum_{k=1}^\infty(1/3)^k e_{t+k}\\
             &= Y_t\\
\end{aligned}
$$
因此满足方程。

### (b)
期望与协方差的计算如下：
$$
E(Y_t) = 0 \\
$$
$$
\begin{aligned}
Cov(Y_t,Y_{t-k}) &= Cov(-\sum_{j=1}^\infty(1/3)^j e_{t+j} , -\sum_{j=1}^\infty(1/3)^j e_{t-k+j}) \\
                 &= Cov(-\sum_{j=1}^\infty(1/3)^j e_{t+j} , -\sum_{j=k+1}^\infty(1/3)^j e_{t-k+j}) \\
                 &= Cov(-\sum_{j=1}^\infty(1/3)^j e_{t+j} , -\sum_{i=1}^\infty(1/3)^{i+k} e_{t+i}) \\
                 &= \sigma_e^2( (\frac{1}{3})^{k+2} + (\frac{1}{3})^{k+4} + \cdots) \\
                 &= \sigma_e^2 \frac{(\frac{1}{3})^{k+2}}{1-(\frac{1}{3})^2} \\
                 &= \frac{\sigma_e^2}{8} (\frac{1}{3})^k
\end{aligned}
$$
可知满足平稳性的定义

### (c)
该解令人不满意的地方在于$Y_t$是取决于未来的误差项，这在实际中无法应用。

## 4.17
### (a)
将该式代入$Y_{t-1}$得：

$$
\begin{aligned}
\frac{1}{2}Y_{t-1}+e_t &= \frac{1}{2}*(10(\frac{1}{2})^{t-1}+e_{t-1}+\frac{1}{2}e_{t-2}+\cdots)+e_t\\
             &= 10(\frac{1}{2})^t+e_t+\frac{1}{2}e_{t-1}+(\frac{1}{2})^2e_{t-2}+\cdots \\
             &= Y_t\\
\end{aligned}
$$
因此是方程的解。

### (b)
由于
$$
E(Y_t) = E(10(\frac{1}{2})^t+e_t+\frac{1}{2}e_{t-1}+(\frac{1}{2})^2e_{t-2}+\cdots) = 10(\frac{1}{2})^t
$$
因此均值对时间并不是常数，所以该解不平稳。

## 4.21
### (a)
$$
Var(Y_t) = \sigma_e^2 + \sigma_e^2 + \frac{1}{4}\sigma_e^2 = \frac{9}{4}\sigma_e^2
$$
$$
\begin{aligned}
Cov(Y_t,Y_{t-1}) &= Cov(e_{t-1}-e_{t-2}+0.5e_{t-3} , e_{t-2}-e_{t-3}+0.5e_{t-4})\\
             &= -\sigma_e^2 - \frac{1}{2}\sigma_e^2 \\
             &= \frac32 \sigma_e^2\\
\end{aligned}
$$
$$
\begin{aligned}
Cov(Y_t,Y_{t-2}) &= Cov(e_{t-1}-e_{t-2}+0.5e_{t-3} , e_{t-3}-e_{t-4}+0.5e_{t-5})\\
             &= 0.5 \sigma_e^2\\
\end{aligned}
$$
其余协方差均为0

### (b)
$\{Y_t\}$ 与 MA(2) 有相同的统计特征。 原因在于误差项是我们无法观测到的，所以就无法区分$Y_t = e_t - e_{t-1} + 0.5e_{t-2}$ 与 $Y_t = e_t' - e_{t-1}' + 0.5e_{t-2}'$,其中$e_t'=e_{t-1}$。 通过计算均值与协方差函数也会发现二者完全相同。

## 4.23
### (a)
$$
\begin{aligned}
Cov(b_t,b_{t-k}) &= Cov(Y_{t}-\phi Y_{t+1} , Y_{t-k}-\phi Y_{t-k+1})\\
                 &= Cov(Y_{t},Y_{t-k}) - \phi Cov(Y_{t+1},Y_{t-k}) -\phi Cov(Y_{t},Y_{t-k+1}) + \phi^2 Cov(Y_{t+1},Y_{t-k+1})\\
                 &= \gamma_k - \phi \gamma_{k+1} -\phi \gamma_{k-1} + \phi^2 \gamma_k\\
                 &= \frac{\sigma_e^2}{1-\phi^2}(\phi^k - \phi \cdot \phi^{k+1} - \phi \cdot \phi^{k-1}+ \phi^2 \cdot \phi^k)\\
                 &= 0\\
\end{aligned}
$$

### (b)
$$
\begin{aligned}
Cov(b_t,Y_{t+k}) &= Cov(Y_t - \phi Y_{t+1} , Y_{t+k})\\
                 &= Cov(Y_t , Y_{t+k}) - \phi Cov(Y_{t+1},Y_{t+k})\\
                 &= \gamma_k - \phi \gamma_{k-1}\\
                 &= \frac{\sigma_e^2}{1-\phi^2}(\phi^k- \phi \cdot \phi^{k-1})\\
                 &= 0\\
\end{aligned}
$$